Create schema IF NOT EXISTS SOMS_WELLBEING;
use SOMS_WELLBEING;

DROP TABLE IF EXISTS ACTIVITY_DATA;
DROP TABLE IF EXISTS ACTIVITY_OUTPUTS;
DROP TABLE IF EXISTS ACTIVITY_LOG;
DROP TABLE IF EXISTS SERVICE_PROVIDER;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ACTIVITY;

CREATE TABLE IF NOT EXISTS `SERVICE_PROVIDER` (
  `SERV_PROV_ID` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NAME` TEXT NOT NULL,
  `EMAIL` TEXT NOT NULL,
  `TELEPHONE` TEXT NOT NULL,
  `ADDRESS` TEXT NOT NULL,
  `POST_CODE` TEXT NOT NULL,
  `COMP_HSE_ID` TEXT
);

CREATE TABLE IF NOT EXISTS `USER` (
  `USER_ID` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `FIRST_NAME` TEXT NOT NULL,
  `LAST_NAME` TEXT NOT NULL,
  `DATE_OF_BIRTH` DATE NOT NULL,
  `EMAIL` TEXT NOT NULL,
  `TELEPHONE` TEXT NOT NULL,
  `ADDRESS` TEXT NOT NULL,
  `POST_CODE` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `ACTIVITY` (
  `ACTIVITY_ID` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `ACTIVITY_NAME` TEXT NOT NULL,
  `SERV_PROV_ID` INTEGER NOT NULL,
  `ACTIVITY_DATE` DATE NOT NULL,
  `DESCRIPTION` TEXT NOT NULL,
  `LOCATION` TEXT NOT NULL,
  `KEYWORDS` TEXT
);

CREATE TABLE IF NOT EXISTS `ACTIVITY_DATA` (
  `ACTIVITY_ID` INTEGER NOT NULL,
  `SERV_PROV_ID` INTEGER NOT NULL,
  `USER_ID` INTEGER,
  `ACTIVITY_DATE` DATE NOT NULL,
  `METRIC_NAME_1` TEXT,
  `METRIC_VALUE_1` TEXT,
  `METRIC_NAME_2` TEXT,
  `METRIC_VALUE_2` TEXT,
  `METRIC_NAME_3` TEXT,
  `METRIC_VALUE_3` TEXT,
  CONSTRAINT ACTIVITY_DATA_FOREIGN FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITY(ACTIVITY_ID)
);

CREATE TABLE IF NOT EXISTS `ACTIVITY_OUTPUTS` (
  `ACTIVITY_ID` INTEGER NOT NULL,
  `SERV_PROV_ID` INTEGER NOT NULL,
  `USER_ID` INTEGER,
  `ACTIVITY_DATE` DATE NOT NULL,
  `OUTPUT_NAME_1` TEXT,
  `OUTPUT_VALUE_1` TEXT,
  `OUTPUT_NAME_2` TEXT,
  `OUTPUT_VALUE_2` TEXT,
  `OUTPUT_NAME_3` TEXT,
  `OUTPUT_VALUE_3` TEXT,
  CONSTRAINT ACTIVITY_OUTPUTS_FOREIGN FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITY(ACTIVITY_ID)
);

CREATE TABLE IF NOT EXISTS `ACTIVITY_LOG` (
  `ACTIVITY_ID` INTEGER NOT NULL,
  `SERV_PROV_ID` INTEGER NOT NULL,
  `USER_ID` INTEGER,
  CONSTRAINT ACTIVITY_LOG_FOREIGN FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITY(ACTIVITY_ID)
);

INSERT INTO SERVICE_PROVIDER (NAME, EMAIL, TELEPHONE, ADDRESS, POST_CODE, COMP_HSE_ID) VALUES ('Biogen', 'biogen@company.com', '09995557777', 'Richmond Road', 'AB62 9LD', '20');
INSERT INTO SERVICE_PROVIDER (NAME, EMAIL, TELEPHONE, ADDRESS, POST_CODE, COMP_HSE_ID) VALUES ('Adidas', 'adidas@company.com', '07775553333', 'Designer Outlet', 'CF32 9SU', '11');
INSERT INTO SERVICE_PROVIDER (NAME, EMAIL, TELEPHONE, ADDRESS, POST_CODE, COMP_HSE_ID) VALUES ('BMW', 'bmw@company.com', '01113335555', 'Park Ln Mayfair London', 'W1K 7TT', '25');

INSERT INTO USER (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, TELEPHONE, ADDRESS, POST_CODE) VALUES ('Jolene', 'Murray', '1980-05-09', 'jolene.murray@user.com', '02224446666', 'Park Street London', 'WC1 5DV');
INSERT INTO USER (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, TELEPHONE, ADDRESS, POST_CODE) VALUES ('Kendra', 'Summer', '1984-06-25', 'kendra.summer@user.com', '01114447777', 'Mill Road London', 'HS57 6KE');
INSERT INTO USER (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, TELEPHONE, ADDRESS, POST_CODE) VALUES ('Jillian', 'Bass', '1980-01-20', 'jillian.bass@user.com', '09999888866', 'Park Street Aberdeen', 'WC1 5DV');
INSERT INTO USER (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, TELEPHONE, ADDRESS, POST_CODE) VALUES ('Frances', 'Baker', '1975-07-10', 'frances.baker@user.com', '04446668888', 'Victoria Street Swindon', 'SN55 8AZ');
INSERT INTO USER (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, TELEPHONE, ADDRESS, POST_CODE) VALUES ('Eric', 'Mendoza', '1990-10-05', 'eric.mendoza@user.com', '08886664444', 'Albert Road', 'BR25 3CV');
INSERT INTO USER (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, TELEPHONE, ADDRESS, POST_CODE) VALUES ('Alessia', 'Villa', '1994-01-09', 'alessia.villa@user.com', '07777555533', 'King Street Portsmouth', 'PO98 5NR');
INSERT INTO USER (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, TELEPHONE, ADDRESS, POST_CODE) VALUES ('Bonita', 'Conway', '1989-12-02', 'bonita.conway@user.com', '04444555566', 'Green Lane London', 'SW5 1PU');
INSERT INTO USER (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, TELEPHONE, ADDRESS, POST_CODE) VALUES ('Marcie', 'Acevedo', '1980-10-20', 'marcie.acevedo@user.com', '01119995555', 'West Street Leicester', 'LE11 7XW');
INSERT INTO USER (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, TELEPHONE, ADDRESS, POST_CODE) VALUES ('Albie', 'Rice', '1987-08-22', 'albie.rice@user.com', '07777666622', 'York Road Harrogate', 'HG75 3HJ');
INSERT INTO USER (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL, TELEPHONE, ADDRESS, POST_CODE) VALUES ('Cassian', 'Wallis', '1995-12-16', 'cassian.wallis@user.com', '08888444411', 'North Street Chelmsford', 'CM62 0KD');

INSERT INTO ACTIVITY (ACTIVITY_NAME, SERV_PROV_ID, ACTIVITY_DATE, DESCRIPTION, LOCATION, KEYWORDS) VALUES ('Rubbish Cleaning', 1, '2020-08-10', 'Cleaning Rubbish around the River Taff', 'Cardiff', '');
